# Generated by Django 5.2.5 on 2025-08-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
