# Generated by Django 5.2.5 on 2025-08-20 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_list_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_list',
            old_name='date',
            new_name='expirity_date',
        ),
        migrations.AddField(
            model_name='todo_list',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
