# Generated by Django 5.2.5 on 2025-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_date_todo_list_expirity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='expirity_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
