# Generated by Django 5.2.5 on 2025-08-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_todo_list_expirity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
